// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/standard-job-workspace/CommandCenter.tsx": () => import("../components/mockups/standard-job-workspace/CommandCenter.tsx"),
  "./components/mockups/standard-job-workspace/Current.tsx": () => import("../components/mockups/standard-job-workspace/Current.tsx"),
  "./components/mockups/standard-job-workspace/JobTabNav.tsx": () => import("../components/mockups/standard-job-workspace/JobTabNav.tsx"),
  "./components/mockups/standard-job-workspace/NeedsAttentionQueue.tsx": () => import("../components/mockups/standard-job-workspace/NeedsAttentionQueue.tsx")
};
