import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/seo";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/creator/",
          "/seeker",
          "/seeker/",
          "/recruit/opportunities",
          "/recruit/opportunities/",
          "/recruit/preview",
          "/recruit/preview/",
          "/recruit/pricing",
          "/recruit/pricing/",
           "/resources",
           "/resources/",
           "/website",
           "/website/",
           "/reviews",
           "/reviews/",
        ],
        disallow: [
          "/api/",
          "/backend/",
          "/billing",
          "/f/",
          "/recruit/analytics",
          "/recruit/assessment",
          "/recruit/auth",
          "/recruit/billing",
          "/recruit/choose-username",
          "/recruit/company-profile",
          "/recruit/copilot",
          "/recruit/dashboard",
          "/recruit/diagnostics",
          "/recruit/forms",
          "/recruit/forgot-password",
          "/recruit/jobs",
          "/recruit/judges",
          "/recruit/login",
          "/recruit/mesh-api-status",
          "/recruit/new",
          "/recruit/offer",
          "/recruit/raka98",
          "/recruit/recruiter",
          "/recruit/reset-password",
          "/recruit/signup",
          "/recruit/status",
          "/recruit/talent-pool",
          "/recruit/team-invite",
          "/recruit/verification",
          "/recruit/verify-email",
          "/seeker/applications",
          "/seeker/billing",
          "/seeker/career",
          "/seeker/cover-letter",
          "/seeker/dashboard",
          "/seeker/email",
          "/seeker/extension",
          "/seeker/interview-prep",
          "/seeker/login",
          "/seeker/profile",
          "/seeker/resume",
          "/seeker/signup",
          "/seeker/tracker",
          "/seeker/workspace",
        ],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
  };
}